---
include:
  - board: xiao_ble//zmk
    shield: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
  - board: xiao_ble//zmk
    shield: totem_dongle
  - board: xiao_ble//zmk
    shield: <totem_dongle> raw_hid_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOXKING=n
  - board: xiao_ble//zmk
    shield: prospector_scanner
    cmake-args: -DEXTRA_CONF_FILE=../../config/prospector_scanner_touch.conf
    artifact-name: prospector_scanner_touch
  - board: xiao_ble//zmk
    shield: settings_reset
